version: "3"

services:

  leagues:
    image: leagues
    build:
      context: .
    ports:
      - 8000-8010:8080
    networks:
      - web
      
  proxy: 
    image: haproxy
    depends_on:
      - leagues
    volumes:
      - './etc/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro'
    ports:
      - 80:80
      - 1936:1936
    networks:
      - web

networks:
  web:
    driver: bridge
